package model


const (
	Domain_pos_ws = "localhost:7630"
)

const (
	//HEART
	HEART_BEAT = "HEART_BEAT"

	//POS
	WS_PAYMENTREQUEST = "WS_PAYMENTREQUEST"
	WS_RESPONSE_SUCCESS = "WS_RESPONSE_SUCCESS"
	WS_RESPONSE_ERROR = "WS_RESPONSE_ERROR"
	WS_POS_NOTIFY = "WS_POS_NOTIFY"

	//disconnect
	WS_DISCONNECT = "WS_DISCONNECT"
)

const (
	WS_CODE_SERVER = 0 //Proactive notification
	WS_CODE_SEND_SUCCESS = 200
	WS_CODE_SEND_ERROR = 400
	WS_CODE_HEART_BEAT = 10
)