package model


var (
	POS_API_Port = ""
	POS_WS_Port = ""
	Domain_POS_WS = "localhost:"+ POS_WS_Port
)

const (
	//HEART
	HEART_BEAT = "HEART_BEAT"

	//POS
	WS_PAYMENTREQUEST = "WS_PAYMENTREQUEST"
	WS_POS_NOTIFY = "WS_POS_NOTIFY"

	//comment
	WS_RESPONSE_SUCCESS = "WS_RESPONSE_SUCCESS"
	WS_RESPONSE_ERROR = "WS_RESPONSE_ERROR"

	//disconnect
	WS_DISCONNECT = "WS_DISCONNECT"
)

const (
	WS_CODE_SERVER = 0 //Proactive notification
	WS_CODE_SEND_SUCCESS = 200
	WS_CODE_SEND_ERROR = 400
	WS_CODE_HEART_BEAT = 10
)