package model


const (
	Domain_wallet_ws = "172.31.168.189:7638"
	Domain_pos_ws = "172.31.168.189:7630"
)

const (
	ASSETTYPE_BSV = "BSV" // BSV交易
	ASSETTYPE_CUR = "CUR" // CUR货币Token交易

	TX_STATE_CREATE = 0
	TX_STATE_BROADCAST = 1
	TX_STATE_OVERTIME = 2

	STATE_EXIST = 1
	STATE_DELETED = 2
)

const (
	//心跳
	HEART_BEAT = "HEART_BEAT"

	//pos
	WS_PAYMENTREQUEST = "WS_PAYMENTREQUEST"
	WS_RESPONSE_SUCCESS = "WS_RESPONSE_SUCCESS"
	WS_RESPONSE_ERROR = "WS_RESPONSE_ERROR"
	WS_POS_NOTIFY = "WS_POS_NOTIFY"

	//wallet
	WS_WALLET_CONNECT = "WS_WALLET_CONNECT"
	WS_API_NOTIFY = "WS_API_NOTIFY"
	WS_WALLET_NOTIFY = "WS_WALLET_NOTIFY"

	//disconnect
	WS_DISCONNECT = "WS_DISCONNECT"
)

const (
	WS_CODE_SERVER = 0 //服务器主动通知

	WS_CODE_SEND_SUCCESS = 200
	WS_CODE_SEND_ERROR = 400

	WS_CODE_HEART_BEAT = 10

)